---
AWSTemplateFormatVersion: "2010-09-09"
Description: for archive S3 Construction
###################################
# --------------------------------#
# Metadata
# --------------------------------#
###################################
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Project Configuration"
        Parameters:
          - SystemId
          - EnvType
          - BillingID
      - Label:
          default: "S3 Configuration"
        Parameters:
          - BucketNameSuffix
          - S3StorageClass
          - S3TransitionDate
          - S3ExpireDate
      - Label:
          default: KMS Configuration(optional)
        Parameters:
          - KMSKeyArn

#---------------------------------#
# Parameters Section
#---------------------------------#
###################################            
Parameters:
  SystemId:
    Type: String
    Description: Enter your system id.
    MinLength: 6
    MaxLength: 6
  EnvType:
    Type: String
    Description: Select the environment.
    AllowedValues:
      - t
      - k
      - v
      - e
      - i
      - s
      - m
      - p
  BillingID:
    Type: String
    Description: Enter the BillingID.

  # S3
  BucketNameSuffix:
    Type: String
    Description: Enter your bucket name s3-(EnvType)-(SystemId)-(BucketNameSuffix).
    MinLength: 1
    Default: log-archive
  S3StorageClass:
    Description: Class of S3 to keep S3 file (Default Standard-IA)
    Type: String
    Default: STANDARD_IA
    AllowedValues:
      - DEEP_ARCHIVE
      - GLACIER
      - Glacier
      - GLACIER_IR
      - INTELLIGENT_TIERING
      - ONEZONE_IA
      - STANDARD_IA
  S3TransitionDate:
    Description: Number of days to transition S3 storage class (Default 90days)
    Type: String
    Default: 90
  S3ExpireDate:
    Description: Number of days to keep S3 file (Default 13month)
    Type: String
    Default: 403
  
  # kms key
  KMSKeyArn:
    Type: String
    Description: Note! For accounts located in the Security Data OU, please enter the arn of your customer key arn.
    AllowedPattern: ^(arn:aws:kms:.*:(\d{12})?:(key|alias)/.+|)\Z

###################################
#---------------------------------#
# Conditions Section
#---------------------------------#
###################################   
Conditions:
  EncryptionByKMS: 
    !Not [!Equals [ !Ref KMSKeyArn, '']] 

###################################
#---------------------------------#
# Resourcecs Section
#---------------------------------#
###################################          
Resources:
  #---------------------------------#
  # S3
  #---------------------------------#
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub s3-${EnvType}-${SystemId}-${BucketNameSuffix}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              !If
              - EncryptionByKMS
              - KMSMasterKeyID: !Ref KMSKeyArn
                SSEAlgorithm: 'aws:kms'
              - SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: !Sub TransitionIn-${S3StorageClass}-${S3TransitionDate}Days
            Status: Enabled
            Transitions:
              - StorageClass: !Ref S3StorageClass
                TransitionInDays: !Ref S3TransitionDate
          - Id: !Sub ExpirationIn-${S3ExpireDate}Days
            Status: Enabled
            ExpirationInDays: !Ref S3ExpireDate
      Tags:
        - Key: SystemId
          Value: !Ref SystemId
        - Key: Environment
          Value: !Ref EnvType
        - Key: Cost1
          Value: !Ref SystemId
        - Key: BillingID
          Value: !Ref BillingID
          
  ArchiveBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Sid: AccessLogFromALB
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::582318560864:root
            Action: 's3:PutObject'
            Resource: !Sub arn:aws:s3:::${S3Bucket}/*

###################################
#---------------------------------#
# Outputs Section
#---------------------------------#
###################################
Outputs:
  S3Bucket:
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${AWS::StackName}-S3Bucket