# provided by DGCP container team
# https://dgcp-ope.backlog.com/projects/DGCP_APP_CONTAINER_RECEPT
AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Parameters:
          - OperationTime
          - TimeZone
          - ECSClusterName
          - ECSServiceName

Parameters:
  OperationTime:
    Type: String
    Description: 'The time to handles automatically Fargate retirement (cron)'
    Default: cron(0 4 ? * SUN *)
  TimeZone:
    Type: String
    Default: Asia/Tokyo
  ECSClusterName:
    Type: String
    Description: 'The name of the ECS Cluster'
  ECSServiceName:
    Type: String
    Description: 'The name of the ECS Service'

Resources:
  EventBridgeSchedulerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'scheduler.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'EventBridgeSchedulerPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'ecs:UpdateService'
                Resource: !Sub 'arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:service/${ECSClusterName}/${ECSServiceName}'
  
  FargateRetirementHandlerScheduleGroup:
    Type: AWS::Scheduler::ScheduleGroup
    Properties:
      Name: !Sub RIHandler-${ECSServiceName}
  
  FargateRetirementHandlerSchedule:
    Type: 'AWS::Scheduler::Schedule'
    Properties:
      FlexibleTimeWindow:
        Mode: 'OFF'
      GroupName: !Ref FargateRetirementHandlerScheduleGroup
      Name: !Sub RIHandler-${ECSServiceName}
      ScheduleExpression: !Ref OperationTime
      ScheduleExpressionTimezone: !Ref TimeZone
      Target:
        Arn: 'arn:aws:scheduler:::aws-sdk:ecs:updateService'
        RoleArn: !GetAtt EventBridgeSchedulerRole.Arn
        Input: !Sub '{"Cluster": "${ECSClusterName}", "Service": "${ECSServiceName}", "ForceNewDeployment": true}'
        RetryPolicy:
          MaximumRetryAttempts: 3
          MaximumEventAgeInSeconds: 60