AWSTemplateFormatVersion: 2010-09-09
Description: CloudwatchLogs to S3 log-rotation
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label:
          default: "Project Configuration"
        Parameters:
          - SystemId
          - EnvType
          - BillingID
      - Label:
          default: "Firehose(Kinesis) Configuration"
        Parameters:
          - LogGroupName
          - S3BucketName
          - SizeInMBs
          - IntervalInSeconds
      - Label:
          default: KMS Configuration(optional)
        Parameters:
          - KMSKeyArn

Parameters:
# project
  SystemId:
    Type: String
    Description: Enter your system id.
    MinLength: 6
    MaxLength: 6
  EnvType:
    Type: String
    Description: Select the environment.
    AllowedValues:
      - t
      - k
      - v
      - e
      - i
      - s
      - m
      - p
  BillingID:
    Type: String
    Description: Enter the BillingID.

  # LogGroupName
  LogGroupName:
    Description: The log group to associate with the subscription filter
    Type: String
    MinLength: 1

  # S3
  S3BucketName:
    Type: String
    Description: Enter your archive bucket name
    MinLength: 1
  
  # Firehose
  SizeInMBs:
    Description: "The size of the buffer, in MBs, that Kinesis Data Firehose uses for incoming data before delivering it to the destination."
    Type: Number
    Default: 5
    MinValue: 1
    MaxValue: 128
  IntervalInSeconds:
    Description: The length of time, in seconds, that Kinesis Data Firehose buffers incoming data before delivering it to the destination. 
    Type: Number
    Default: 300
    MinValue: 60
    MaxValue: 900
  
  # kms key
  KMSKeyArn:
    Type: String
    Description: Note! For accounts located in the Security Data OU, please enter the arn of your customer key arn.
    AllowedPattern: ^(arn:aws:kms:.*:(\d{12})?:(key|alias)/.+|)\Z

###################################
#---------------------------------#
# Conditions Section
#---------------------------------#
###################################   
Conditions:
  EncryptionByKMS: 
    !Not [!Equals [ !Ref KMSKeyArn, '']] 

Resources:
#--------------------------------------------------#
# subscription_filter_role
#--------------------------------------------------#
  SubscriptionFilterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub logs.${AWS::Region}.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: subscription_filter_policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - firehose:PutRecord
                  - firehose:PutRecords
                Resource: !GetAtt DeliveryStream.Arn

#--------------------------------------------------#
# firehose_delivery_role
#--------------------------------------------------#
  DeliveryRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref AWS::AccountId
      Policies:
        - PolicyName: firehose_delivery_policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Resource:
                  - !Sub arn:aws:s3:::${S3BucketName}
                  - !Sub arn:aws:s3:::${S3BucketName}*
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: '*'
      Tags:
        - Key: SystemId
          Value: !Ref SystemId
        - Key: Environment
          Value: !Ref EnvType
        - Key: Cost1
          Value: !Ref SystemId
        - Key: BillingID
          Value: !Ref BillingID

#--------------------------------------------------#
# SubscriptionFilter
#--------------------------------------------------#
  SubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties: 
      DestinationArn: !GetAtt DeliveryStream.Arn
      FilterName: log-rotation-filter
      FilterPattern: ''
      LogGroupName: !Ref LogGroupName
      RoleArn: !GetAtt SubscriptionFilterRole.Arn

#--------------------------------------------------#
# Firehose DeliveryStream
#--------------------------------------------------#
  DeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Join [_, !Split [/, !Sub "logs-${LogGroupName}-delstream"]]  
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: !Sub arn:aws:s3:::${S3BucketName}
        BufferingHints:
          SizeInMBs: !Ref SizeInMBs
          IntervalInSeconds: !Ref IntervalInSeconds
        CompressionFormat: GZIP
        CustomTimeZone: Asia/Tokyo
        EncryptionConfiguration:
            !If
            - EncryptionByKMS
            - KMSEncryptionConfig: 
                AWSKMSKeyARN: !Ref KMSKeyArn
            - NoEncryptionConfig: NoEncryption
        Prefix: !Join [/, !Split [//, !Sub "logs/${LogGroupName}"]]
        RoleARN: !GetAtt DeliveryRole.Arn
      Tags:
        - Key: SystemId
          Value: !Ref SystemId
        - Key: Environment
          Value: !Ref EnvType
        - Key: Cost1
          Value: !Ref SystemId
        - Key: BillingID
          Value: !Ref BillingID